### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by jgillich** [watzon/marionette#14]
Puppeteer has the ability to export a page to a PDF, and that feature was [recently added](https://hg.mozilla.org/mozilla-central/rev/44c5a2312fd6) to Firefox as well.

Is it possible to support this in Marionette? As far as I can tell, the WebDriver protocol does not support this feature.

**Comment by watzon** [comment]
If it's not a feature supported by webdriver that's a no. Puppeteer uses
the DevTools protocol, which allows it to do a lot more than we can with
webdriver. I wanted to wrap DevTools as well at first, but dealing with
event based IO like WebSockets in Crystal is a pain right now.

**Comment by jgillich** [comment]
> dealing with event based IO like WebSockets in Crystal is a pain right now

Can you tell me more about that? I might actually build this.

**Comment by watzon** [comment]
So there's two libraries you might look at right now. I considered doing this again, but I've been working on other things. The first is [playwright](https://github.com/microsoft/playwright) which is a newer project by Microsoft that's supposed to be "the new puppeteer". And there's [puppeteer](https://github.com/puppeteer/puppeteer) itself which is a Google project. I'd focus on replicating the functionality of playwright if I were you. Google also has decent [API documentation](https://chromedevtools.github.io/devtools-protocol/) for the Devtools Protocol.

**Comment by jgillich** [comment]
Thank you, I will check it out. I think this can be closed.
