### ISSUE TITLE
Launcher does not provide enough time to start Firefox

### ISSUE THREAD

**Issue by ikaru5** [watzon/marionette#18]
On launch I get an `Unhandled exception: Error connecting to '127.0.0.1:2828': Connection refused (Socket::ConnectError)`.

I'm running on an ssd and a fast Ryzen CPU, so firefox starts pretty fast.

To quickfix this for me I added a `sleep 3` in `launcher.cr` on line 81 like this:

```crystal
        # ...
        stderr ||= Process::ORIGINAL_STDERR
        Process.new(executable.to_s, args, env, output: stdout, error: stderr)
        sleep 3
      end

      browser = Browser.new(address, port, extended, timeout)
      # ...
```

**Comment by watzon** [comment]
Yeah this could likely be improved. Really we should have a timeout of some kind and then have it keep checking for a connection until the timeout is hit.

**Comment by ikaru5** [comment]
Made a PR to this issue too. :)
I'm still new to Crystal. Not sure if it could be done more beautiful.

**Comment by watzon** [comment]
I'll go ahead and merge for now, but I'm going to leave this issue open until I have a better fix

**Comment by watzon** [comment]
The better fix is coming. Keep posted, but I'm doing a full rewrite of Marionette.

**Comment by watzon** [comment]
Ok well this should be fixed big time. Major overhaul just happened.
