### ISSUE TITLE
Support unicode for filling forms

### ISSUE THREAD

**Issue by sclee15** [watzon/marionette#2]
Hello. I tried to fill a value with keyboard input.
English is OK. but it seems it doesn't accept other languages.
I think it is encoding problem.
I hope I can fill it with various languages.

Thank you.

**Comment by watzon** [comment]
It should work, so that's weird. Could you provide the input, expected output, and actual output? Ideally supply a small working code sample as well.

**Comment by sclee15** [comment]
`require "marionette"

Marionette.launch(headless: false) do
  goto("http://google.com")
  elem = find_element(Marionette::Browser::LocatorStrategy::XPATH, "//*[@id=\"tsf\"]/div[2]/div/div[1]/div/div[1]/input")
  elem.send_keys(["한국어"])
  save_screenshot("watzon-tech.jpg")
  sleep 7000
  # elem = find_element(Marionette::Browser::LocatorStrategy::ID, "password")
  # elem.send_keys("teamwork")
end`

**Comment by sclee15** [comment]
require "marionette"

Marionette.launch(headless: false) do
  goto("http://google.com")
  elem = find_element(Marionette::Browser::LocatorStrategy::XPATH, "//*[@id=\"tsf\"]/div[2]/div/div[1]/div/div[1]/input")
  elem.send_keys(["한국어"])
  save_screenshot("watzon-tech.jpg")
  sleep 7000
  # elem = find_element(Marionette::Browser::LocatorStrategy::ID, "password")
  # elem.send_keys("teamwork")
end

**Comment by sclee15** [comment]
require "marionette"

Marionette.launch(headless: false) do
  goto("http://google.com")
  elem = find_element(Marionette::Browser::LocatorStrategy::XPATH, "//*[@id=\"tsf\"]/div[2]/div/div[1]/div/div[1]/input")
  elem.send_keys(["한국어"])
  save_screenshot("watzon-tech.jpg")
end

**Comment by watzon** [comment]
So I think you may need to try something more along these lines:

```crystal
Marionette.launch(headless: false) do
  goto("http://google.com")
  elem = find_element(:xpath, "//input[@name='q']")
  elem.try &.send_keys("한국어")
  save_screenshot("google.jpg")
end
```

Keep in mind these things:
1. `find_element` may return `nil` if no element was found, therefore you should be using `try` with `elem`
2. `send_keys` accepts a number of strings as arguments, no need to do an Array

I just realized that `find_element` also has a bug in the latest `master` version, so I'll update it right now and make a new patch release

**Comment by watzon** [comment]
@sclee15 please let me know if that works for you. It worked in my tests.

**Comment by sclee15** [comment]
Awesome it works thanks.
