### ISSUE TITLE
external cookie file

### ISSUE THREAD

**Issue by wontruefree** [watzon/marionette#22]
I have a cookie file I want to use so I dont have to auth everything.  Is there a way to use an external cookie file?

**Comment by watzon** [comment]
So webdriver itself does have an AddCookie action which could be used to add individual cookies, but I just realized that I forgot to wrap that action with a method. I'll see if I can get that done.

**Comment by wontruefree** [comment]
did this get merged?

**Comment by watzon** [comment]
I haven't had time recently to do any work on this

**Comment by wontruefree** [comment]
no worries I just wanted to check

**Comment by watzon** [comment]
Finally got around to this. Sorry it took so long.
