### ISSUE TITLE
How to remove everything but the web page content area?

### ISSUE THREAD

**Issue by drhuffman12** [watzon/marionette#23]
I'd like to make the page full screen, disable `F11`, and not show the `Chrome is being controlled by automated test software` notification.

* I can get the fullscreen part via:
```
      options = Marionette.chrome_options(args: ["start-fullscreen"])
      session = Marionette::WebDriver.create_session(:chrome, exe_path: webdriver_path, capabilities: options)
```

* I'm not sure how to disable `F11`.

* This link looks helpful for removing the `Chrome is being ...` part, but I'm not sure how it translates to `marionette`:

https://help.applitools.com/hc/en-us/articles/360007189411--Chrome-is-being-controlled-by-automated-test-software-notification

**Comment by watzon** [comment]
This is a little outside the scope of this project as an automation tool, however if you can figure out how to do the things mentioned please feel free to explain here as it could be helpful for other people.

**Comment by watzon** [comment]
So this is actually possible using the `chrome_options(experimental_options)` argument. Here's an example:

```crystal
options = Marionette.chrome_options(experimental_options: {"excludeSwitches" => ["enable-automation"]})
session = Marionette::WebDriver.create_session(:chrome, capabilities: options)
# ...
```
