### ISSUE TITLE
compatibility with Crystal 1.0.0

### ISSUE THREAD

**Issue by MarioRuiz** [watzon/marionette#27]
any ETA when will be compatible with Crystal 1.0.0?

**Comment by watzon** [comment]
I just haven't had time to work on any personal projects lately, but I would be happy to merge a PR that adds support

**Comment by straight-shoota** [comment]
I'd expect this shard is probably already compatible with 1.0, it just doesn't say so in the shard.yml

**Comment by watzon** [comment]
There's a good chance of that. I'll give it a test.

**Comment by watzon** [comment]
Can confirm that it already seems compatible with 1.0.0. Updated shard.yml and .tool-versions to reflect this. Thanks :)
