### ISSUE TITLE
Find elements is broken

### ISSUE THREAD

**Issue by kholbekj** [watzon/marionette#35]
`find_elements` crashes with
```

In lib/marionette/src/marionette/session.cr:456:10

 456 | if parent
          ^-----
Error: undefined local variable or method 'parent' for Marionette::Session
```

Fixing that (by adding parent to parameters) raises a new error because ids are not hooked up right. I think the method needs a look, looks like the "Huge update" in november broke some stuff

**Comment by felixding** [comment]
Same here. Took me awhile until I found this issue.
