### ISSUE TITLE
Screenshot returning nil?

### ISSUE THREAD

**Issue by watzon** [watzon/marionette#4]
Putting this here so I can show progress. cc: @bararchy 

Apparently there is a situation where screenshot might return nil

```
Error in Cross-Site Scripting entry_point http://vulnerable-bank.com/app_v3_banking.php: Expected Hash for #[](key : String), not Nil (Exception)

  from /usr/share/crystal/src/json/any.cr:104:7 in '[]'

  from lib/marionette/src/marionette/browser.cr:594:14 in 'screenshot'

  from /usr/share/crystal/src/fiber.cr:255:3 in 'run'

  from ???
```

**Comment by watzon** [comment]
It's possible that 23144c8 will fix this, but I wasn't able to reproduce using http://vulnerable-bank.com/app_v3_banking.php so I can't test for sure

**Comment by bararchy** [comment]
:+1: thanks :)

**Comment by bararchy** [comment]
Seems this issue is still in effect

```crystal
Expected Hash for #[](key : String), not Nil (Exception)
  from /usr/share/crystal/src/json/any.cr:104:7 in '[]'
  from lib/marionette/src/marionette/browser.cr:594:14 in 'screenshot'
```

I think it might not actually be the URL as it just might be the state the browser is in.
I'll try and produce more helpful info regarding this occurrence.
